on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

        # Specify inline Bun version.
        with:
          bun-version: 1.1.19

      - name: Install dependencies
        run: bun install

      - name: Print version
        run: bun --version

