on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

        # Use Bun version from the `.bun-version`.
        with:
          bun-version-file: .bun-version

      - name: Install dependencies
        run: bun install

      - name: Print version
        run: bun --version

