on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Use the latest version of Bun if not specified.
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Print version
        run: bun --version

